#!/bin/sh

HOOK=.git/hooks/pre-commit
test -f $HOOK && echo "$HOOK already exists." && exit 1

cat >$HOOK <<'EOF'
#!/bin/sh
# Get revision to diff against.
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached $against -- || exit 1

# Install the repoeol with:
#   go install github.com/tajtiattila/repoeol

# Ensure MSVC source files use CRLF
repoeol -crlf .c,.cpp,.h,.rc,.inl || exit 1
EOF
